### ISSUE TITLE
Using no-undef-promise?

### ISSUE THREAD

**Issue by xjamundx** [colonyamerican/eslint-plugin-cah#3]
I created an eslint plugin called `eslint-plugin-promise` and someone has asked for a rule really similar to your `no-undef-promise`.

Do you mind if we bring that over into our plugin? I'll give you attribution in the README and in the sourcecode if you want. 

See the related issue here:
https://github.com/xjamundx/eslint-plugin-promise/issues/2

**Comment by jbrumwell** [comment]
No issues here @xjamundx :)

**Comment by xjamundx** [comment]
:+1:
